pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

include 'affix'
include 'unique'
include 'combat'
include 'zones'
include 'currency'
include 'crafting'

project(':affix').projectDir = file('src/affix')
project(':unique').projectDir = file('src/unique')
project(':combat').projectDir = file('src/combat')
project(':zones').projectDir = file('src/zones')
project(':currency').projectDir = file('src/currency')
project(':crafting').projectDir = file('src/crafting')
